# Generated by Django 2.1.7 on 2019-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_on', models.DateTimeField()),
                ('mobile_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('content', models.CharField(blank=True, default=None, max_length=1500, null=True)),
            ],
        ),
    ]
